language: node_js

branches:
  only:
    - master

cache:
  directories:
    - node_modules
 
node_js:
  - stable
 
install:
  - npm install
 
script:
  - npm run lint:travis
  - npm test
  - npm run coveralls